name: publish
on:
  workflow_run:
    workflows: [publish]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://pull.dovatvis.nl?service=${{github.event.repository.name}}&path=/home/david/servers&token=${{secrets.PULL_TOKEN}}'
          method: 'GET'
          timeout: '600000'
